### ISSUE TITLE
Update function not working in Ajax Post Request

### ISSUE THREAD

**Issue by julia-pearson-15** [julia-pearson/peoples_park#1]
Working functionality so far:

I have my map up and running so that: 
- users can see a map of available spots
- if they click on the spot they see an information window about the spot
- they see a link to take the spot
- an event listener calls a preventDefault() on the link and an AJAX POST request that sends along the spot object
- the server picks up the POST request and successfully receives the spot object in the req.body

Trying to get to work:
- find the right object in the DB and update it's "status" key to "taken"

Code from app.js :

```
app.post('/taken', function(req, res){
   var takenSpot = req.body.spot;
   db.collection('spots').update({_id: takenSpot._id},{$set: {day : 'taken'}}, function(err, data) {
     res.json(data);
   });
});
```

I have console.logged 'takenSpot' and it is the spot object i.e.

```
{ _id: '56a263069cd42361a47626d8',
  location: { lat: '40.6672681', lng: '-73.9887921' },
  day: 'Monday',
  leaving: '2016-01-20T18:11:13+00:00',
  status: 'expiring' }
```

but the return in the json is : Object `{ok: 1, nModified: 0, n: 0}` and the spot object is not updated

Code from main.js where AJAX call is made:

```
  marker.addListener('click', function(event) {
    infowindow.open(map, marker);
    $('#take-spot').on('click', function(event){
      //stop link in info box from workign
      event.preventDefault();
      $.ajax({
        url: '/taken',
        type: 'POST',
        dataType: 'json',
        data: {spot: location}
      }).done(function(response){console.log(response);});
    });
  });
```

**Comment by phlco** [comment]
the problem is trying to find it by the object id. 

remember there's a difference between _id: ObjectId("5645") and _id: "5645"

you'll have to pull in the ObjectId method and call it

**Comment by julia-pearson-15** [comment]
Thank you!!
